title: this button doesnt work idk why

description: >- # this means to ignore newlines until "baseurl:"
  Analysis Notes
baseurl: "/Folland-Reading" # the subpath of your site, e.g. /blog
url: "https://bighappysloth.github.io" # the base hostname & protocol for your  site, e.g. http://example.com

github_username:  bighappysloth

timezone: America/Toronto
livereload: true

markdown: kramdown
kramdown:
  math_engine: katex
  

# Build settings
theme: jekyll-text-theme
  

plugins:
  - jekyll-feed
  - jekyll-toc

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
