name: Building PDF from Source...
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
      
          # The root LaTeX file to be compiled
          root_file: "*.tex"
          glob_root_file: true
          working_directory: ./

          # Interpret the root_file input as bash glob pattern
          # glob_root_file: # optional

          # The working directory for this action
          # working_directory: # optional

          # The LaTeX engine to be invoked
          # compiler: # optional, default is latexmk

          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -f

          # Install extra packages by apk
          # extra_system_packages: # optional

          # Install extra .ttf/.otf fonts.
          # extra_fonts: ./fonts/*.ttf

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # pre_compile: tlmgr update --self && tlmgr update --all # disabling updates

          # Arbitrary bash codes to be executed after compiling LaTeX documents
          post_compile: latexmk -c

          # Instruct latexmk to enable --shell-escape
          # latexmk_shell_escape: # optional

          # Instruct latexmk to use LuaLaTeX
          # latexmk_use_lualatex: # optional

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '

    - name: Upload PDF files
      uses: actions/upload-artifact@v2
      with:
        name: PDFs
        path: |
          **/*.pdf
