name: Compile Section PDFs and push to gh-pages.
on: 
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Document
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          working_directory: "./"
          glob_root_file: true
          root_file: "**/*Compiled.tex"
          
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # pre_compile: tlmgr update --self && tlmgr update --all # disabling updates

          # Cleanup
          post_compile: latexmk -c

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 
          
    - name: Copy PDFs to Temp Directory
      run: |
        mkdir out
        cp "**/*.pdf" "./out/"

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        CLEAN: true
        SINGLE_COMMIT: true
        FOLDER: out
        GIT_CONFIG_NAME: bighappysloth
        GIT_CONFIG_EMAIL: ting.h.li@mail.mcgill.ca
