name: Build PDFs from .tex files and update gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
          
    - name: Build sub-chapters
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          working_directory: "./"
          glob_root_file: true
          root_file: "**/*Compiled.tex"
          
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # pre_compile: tlmgr update --self && tlmgr update --all # disabling updates

          # Cleanup
          post_compile: latexmk -c

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 
          
    - name: Build main-documents
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          working_directory: "./"
          glob_root_file: true
          root_file: "main*.tex"
          
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # pre_compile: tlmgr update --self && tlmgr update --all # disabling updates

          # Cleanup
          post_compile: latexmk -c

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Move PDFs to ./out
      run: |
        mkdir -p out
        find . -type f -name "*Compiled.pdf" -exec mv {} out/ \;
        find . -type f -name "main*.pdf" -exec mv {} out/ \;

    - name: Upload PDFs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled_pdfs
        path: out

  update_gh_pages:
    runs-on: ubuntu-latest
    needs: build_pdfs

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Download PDFs artifact
      uses: actions/download-artifact@v3
      with:
        name: compiled_pdfs
        path: ~/download/

    - name: Move PDFs to the repository
      run: |
        mkdir -p ./docs/download
        mv ~/download/* ./docs/download/

    - name: Set up Git user
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update PDFs" || true
        git push
