name: Github Actions CI to build pdf from tex source.
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
          # The root LaTeX file to be compiled
          working_directory: "./"
          root_file: |
            "main.tex"
          work_in_root_file_dir: false
          glob_root_file: true

          # The working directory for this action
          
          

          # The LaTeX engine to be invoked
          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

          # Install extra packages by apk
          # extra_system_packages: # optional

          # Install extra .ttf/.otf fonts.
          # extra_fonts: ./fonts/*.ttf

          # Arbitrary bash codes to be executed before compiling LaTeX documents
          pre_compile: tlmgr update --self && tlmgr update --all # disabling updates

          # Arbitrary bash codes to be executed after compiling LaTeX documents
          # Cleanup
          post_compile: latexmk -c

          # Instruct latexmk to use XeLaTeX
          latexmk_use_xelatex: true 

    - name: Check pdf file
      run: |
        file main.pdf | grep -q ' PDF '

    - name: Upload file to repository
      run: |
        git config --global user.name "bighappysloth"
        git config --global user.email "ting.h.li@mail.mcgill.ca"
        git add -f "*.pdf"
        git commit -m "Generated PDF Files."
        git push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
